apiVersion: v1
kind: Service
metadata:
  name: aiinteractionservice
spec:
  selector:
    app: aiinteractionservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  