apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizservice
  labels:
    app: quizservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quizservice
  template:
    metadata:
      name: quizservice
      labels:
        app: quizservice
    spec:
      containers:
        - name: quizservice
          image: vakdevi/quizservice:v0.01
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      